export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST"
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS"
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL"

export const ALL_CATEGORIES_REQUEST = "ALL_CATEGORIES_REQUEST"
export const ALL_CATEGORIES_SUCCESS = "ALL_CATEGORIES_SUCCESS"
export const ALL_CATEGORIES_FAIL = "ALL_CATEGORIES_FAIL"

export const QUESTION_REQUEST = "QUESTION_REQUEST"
export const QUESTION_SUCCESS = "QUESTION_SUCCESS"
export const QUESTION_FAIL = "QUESTION_FAIL"
export const GET_NEXT_QUESTION = "GET_NEXT_QUESTION"

export const ADD_QUESTION_REQUEST = "ADD_QUESTION_REQUEST"
export const ADD_QUESTION_SUCCESS = "ADD_QUESTION_SUCCESS"
export const ADD_QUESTION_FAIL = "ADD_QUESTION_FAIL"

export const DASHBOARD_QUESTION_REQUEST = "DASHBOARD_QUESTION_REQUEST"
export const DASHBOARD_QUESTION_SUCCESS = "DASHBOARD_QUESTION_SUCCESS"
export const DASHBOARD_QUESTION_FAIL = "DASHBOARD_QUESTION_FAIL"

export const QUESTION_CATEGORY_REQUEST = "QUESTION_CATEGORY_REQUEST"
export const QUESTION_CATEGORY_SUCCESS = "QUESTION_CATEGORY_SUCCESS"
export const QUESTION_CATEGORY_FAIL = "QUESTION_CATEGORY_FAIL"


export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"
export const USER_LOGOUT = "USER_LOGOUT"